# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - # The 'replacements' field has been removed in v2.
    # You need to use template functions in 'name_template' instead.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
snapcrafts:
  -
    id: tanda
    name: tanda
    publish: true
    summary: Versioning your flutter project follow standard semantic version.
    description: >
      `tanda` is a command line tool that will help you versioning your flutter project.
    # Need to use classic because `tanda` need to read file from other place
    # confinement: classic
    # Using confinement strict with access to home directory interface
    confinement: strict
    apps:
      tanda:
        plugs:
          - home
    channel_templates:
      - stable

release:
  github:
    owner: fakhrullah
    name: tanda

  # draft: true